name             'jbox-postgresql'
maintainer       'Nicolas Rodriguez'
maintainer_email 'nico@nicoladmin.fr'
license          'MIT'
description      'Installs/Configures Postgresql'
version          '1.0.0'
